### ISSUE TITLE
app/middleware/mongoose.js should have this change

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/express-template#48]
per @payne-chris-r  in 016 delivery. 

The wiring has moved since the last update to this template. 

app/middleware/mongoose.js

```diff
'use strict';

- const database = require('../../config/database');
+ const database = require('config/database');
const mongoose = require('mongoose');
const uri = process.env.MONGODB_URI || database.mongoose.uri;
mongoose.Promise = global.Promise;
mongoose.connect(uri);

module.exports = mongoose;
```

Though this may not be necessary, see @bernardlee 's comment below.

**Comment by bernardlee** [comment]
Ben and I were going through this repository together last week (2017-03-03) to figure out why MongoDB wasn't working during the deployment process.  We saw the line `const database = require('config/database');` as we were going through the stack trace and thought that it might have been an error since `require()` needs relative paths to resolve non-packaged files, but it turns out that Antony wrote a loading library to resolve paths like this so that there aren't any problems when running this application with `./bin/express server`.  I think that there were problems during the talk because the files were being run in the command line interface (e.g. `node ./bin/aws-upload.js ...`).

**Comment by payne-chris-r** [comment]
See diff here: https://github.com/payne-chris-r/express-api-upload/commit/f44a826a3c12e0a569113b73055ec1d461fd5d50

**Comment by payne-chris-r** [comment]
This is actually baked in to express template and just means you have to set NODE_PATH to $PWD before running the script.

**Comment by payne-chris-r** [comment]
Question. What if in `scripts` portion of package.json we changed "node" to set PWD, then run node?

**Comment by BenGitsCode** [comment]
Ah that makes sense. Thanks for the clarification @payne-chris-r

**Comment by payne-chris-r** [comment]
"scripts": {
    "start": "./bin/express server",
    "run": "NODE_PATH... node "???
  },

**Comment by gaand** [comment]
That can't work, unfortunately.  We'd need to wire something up with `grunt`.
